### ISSUE TITLE
Wierd firefox bug

### ISSUE THREAD

**Issue by forivall** [wulkano/getkap.co#1]
On retina screen:
<img width="1011" alt="screen shot 2016-10-05 at 10 29 25 am" src="https://cloud.githubusercontent.com/assets/760204/19124110/a2e63a56-8ae6-11e6-9961-197cc50d8bbd.png">

On traditional screen:
![screen shot 2016-10-05 at 10 31 02 am](https://cloud.githubusercontent.com/assets/760204/19124144/d48010e6-8ae6-11e6-9110-58a6f2e2692b.png)

FF 49.0, OS X 10.11.6 (El Capitan)

Also:
<img width="712" alt="screen shot 2016-10-05 at 10 33 24 am" src="https://cloud.githubusercontent.com/assets/760204/19124217/1e1fa5d6-8ae7-11e6-8f28-e951d2cfdbcd.png">

I'm curious if this is in the firefox bugtracker.

**Comment by timothyis** [comment]
Wow, thanks for catching this @forivall! I don't know how I missed it. 😨
