### ISSUE TITLE
Mention that only OSX/MacOS

### ISSUE THREAD

**Issue by tomByrer** [wulkano/getkap.co#10]
Looks like Windows & Linux compatibility won't happen for a long time, if ever.

**Comment by skllcrn** [comment]
There are open issues for both, see https://github.com/wulkano/kap/issues/20, https://github.com/wulkano/kap/issues/31 and https://github.com/wulkano/aperture.js/pull/7.

**Comment by timothyis** [comment]
Hi there @tomByrer. We actually do explicitly state that Kap is OSX/Mac OS only in both places that we offer downloads.

![image](https://cloud.githubusercontent.com/assets/1695613/21229540/d0d6e19c-c2d9-11e6-9994-bde41fbe1633.png)

![image](https://cloud.githubusercontent.com/assets/1695613/21229554/da722a40-c2d9-11e6-9aa6-8065ddc79451.png)

**Comment by tomByrer** [comment]
Thanks for the fast feedback!
I was thinking about something near the the big, green, "Get App" button on your website, which IMHO is the most obvious download link.    There is a faded gray specs 4 elements away, maybe that can be bolder & moved closer?
![getkap co](https://cloud.githubusercontent.com/assets/1308419/21234638/0f36ef52-c2b9-11e6-9123-2c145867bb05.jpg)
