### ISSUE TITLE
Download image has height zero in Firefox

### ISSUE THREAD

**Issue by forivall** [wulkano/getkap.co#2]
<img width="199" alt="screen shot 2016-10-05 at 10 38 14 am" src="https://cloud.githubusercontent.com/assets/760204/19124384/db92091a-8ae7-11e6-8dd9-7b010a3dfe29.png">

**Comment by timothyis** [comment]
@forivall I'm in the middle of fixing this right now. Thanks! ❤️ 

Also: dammit firefox

**Comment by timothyis** [comment]
Thanks again!
