### ISSUE TITLE
High cpu usage of Kap website

### ISSUE THREAD

**Issue by xiebruce** [wulkano/getkap.co#42]
Once I open and scroll the webpage, the CPU usage of [https://getkap.co](https://getkap.co) raise to 18.x% to 19.x%, I think it's unnormal.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/13575500/122325623-84b08080-cf5d-11eb-814c-43387ba0663b.png">

macOS: `macOS Big Sur 11.2.3`
Safari: `Version 14.0.3 (16610.4.3.1.7)`

**Comment by timothyis** [comment]
Thanks for pointing this out! Would you mind testing this again? We've release some performance improvements today. 🙏🏼

**Comment by timothyis** [comment]
Testing this again, it seems this is still an issue due to (I think) the CSS animation, which is strange. I'll try to do some tests for this and if there's a way to lower the usage.

**Comment by xiebruce** [comment]
It's still the same, maybe it doesn't matter, it seems this is happening in any webpage when you scrolling them, the only difference is some take up more cpu and some take up less. 19% or 20% is just more than common webpage take up, say this github page which I'm replying you.

**Comment by timothyis** [comment]
Going to close this since we can't reliably test it and no other reports
